# Generated by Django 6.0.4 on 2026-05-21 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='회차')),
                ('sales_start', models.DateTimeField(verbose_name='판매 시작')),
                ('sales_end', models.DateTimeField(verbose_name='판매 종료')),
                ('is_drawn', models.BooleanField(default=False, verbose_name='추첨 완료')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '회차',
                'verbose_name_plural': '회차',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='DrawResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_numbers', models.JSONField(verbose_name='당첨 번호')),
                ('bonus_number', models.PositiveIntegerField(verbose_name='보너스 번호')),
                ('drawn_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draw_result', to='lottery.round')),
            ],
            options={
                'verbose_name': '추첨 결과',
                'verbose_name_plural': '추첨 결과',
                'ordering': ['-drawn_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.JSONField(verbose_name='선택 번호')),
                ('purchase_type', models.CharField(choices=[('manual', '수동'), ('auto', '자동')], max_length=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='lottery.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '복권',
                'verbose_name_plural': '복권',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
